#数据源连接信息
spring:
  redis:
    host: 43.138.64.89
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
  datasource:
    username: user
    password: user
    url: jdbc:mysql://43.138.64.89:3300/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5

server:
  port: 8080
